config/routes.rb
VotaPrato::Application.routes.draw do
  
  devise_for :users

  resources :comentarios


  resources :qualificacoes
  
  resources :restaurantes
  
  resources :clientes


  #Aqui aponta para o index, para a página inicial
  root :to => "welcome#index"

end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index,:show]

  
  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
    @qualificacao = Qualificacao.find(params[:id])
    #respond_with @qualificacao
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.json
  def new
    @qualificacao = Qualificacao.new
    #respond_with @qualificacao
  end
  
  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao criada com sucesso.' }
        format.json { render json: @qualificacao, status: :created, location: @qualificacao }
      else
        format.html { render action: "new" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to @qualificacao, notice: 'Qualificacao atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to qualificacoes_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualificacoes
      @qualificacao = Qualificacao.find(params[:id])
    end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
        <% @qualificacao.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @qualificacao.cliente %>
    <%= f.hidden_field 'cliente_id' %>
    <% else %>
    <p><font color="darkgrey" size="6"><%= f.label :cliente_id %><br /></font>
    <%= f.collection_select(:cliente_id, Cliente.order('nome'), :id, :nome, {:prompt => true}) %></p>
<%end%>
  </div>

  <div class="field">
    <% if @qualificacao.restaurante %>
    <%= f.hidden_field 'restaurante' %>
    <%else%>
    <p><font color="darkgrey" size="6"><%= f.label :restaurante_id %><br /><font>
      <%= f.collection_select(:restaurante_id, Restaurante.order('nome'), :id, :nome, {:prompt => true}) %></p>
    <%end%>
  </div>

  <div class="field">
    <font color="darkgrey" size="6"><%= f.label :nota %><br /></font>
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <font color="darkgrey" size="6"><%= f.label :valor_gasto %><br /></font>
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1 align="center"><font color="#9B1C26">Editing qualificacao</font></h1>

<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td>
		<font size="6">
<%= link_to 'Mostrar', @qualificacao %> |
<%= link_to 'Voltar', qualificacoes_path %>
		</font>
	</td>
</table>

app/views/qualificacoes/index.html.erb
<h2 class="center">Lista de Qualificacoes</h2>
<br>
<table class="table table-striped table-bordered table-hover center">
  <tr>
    <th>Cliente</th>
    <th>Restaurante</th>
    <th>Nota</th>
    <th>Valor gasto</th>
  </tr>
<% @qualificacoes.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.restaurante.nome %></td>
    <td><%= qualificacao.nota %></td>
    <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
    <td><%= link_to 'Mostrar', qualificacao %></td>
    <td><%= link_to 'Editar', edit_qualificacao_path(qualificacao) %></td>
    <td><%= link_to 'Remover', qualificacao, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>
<br>
<b><%= link_to 'Nova Qualificação', action: 'new' %></b>

app/views/qualificacoes/new.html.erb
<h1 align="center" class="titulo"><font color="#9B1C26">New qualificacao</font></h1>

<br>

<table align="center">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<br>
<br>
<br>

<table align="center">
	<td>
		<font size="6">
<%= link_to 'Voltar', qualificacoes_path %>
		</font>
	</td>
</table>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<table align="center">
	<tr>
		<td>
<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente_id %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante_id %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<tr>
		<td>
<%= link_to "Nova qualificacao", :controller => 'qualificacoes', 
:action => "new",
:cliente => @cliente %>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<tr>
		<td>
			
<%= novo_comentario(@qualificacao) %>
			
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td>
		
<%= link_to 'Editar', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Voltar', qualificacoes_path %>
		
	</td>
</table>


<% unless @qualificacao.comentarios.empty?%>
<%= comentarios @qualificacao %>
<%end%>